Update CMakeLists.txt
Couldn't commit, some unintelligible error message, so had to edit file directly. Here wer the error messages:

PS D:\buildroadrunner\roadrunner\wrappers\C> git pull
error: Your local changes to the following files would be overwritten by merge:
        docs/OriginalDoxygenStyleDocs/html/index.html
Please commit your changes or stash them before you merge.
Aborting

I try to commit but then get

On branch develop
Your branch and 'origin/develop' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)